# Generated by Django 2.2.1 on 2019-06-24 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.CharField(max_length=200)),
                ('movie_poster', models.ImageField(upload_to='')),
                ('genre', models.CharField(max_length=100)),
                ('release_date', models.CharField(max_length=100)),
                ('running_time', models.CharField(max_length=50)),
                ('nomination_prize', models.CharField(max_length=200)),
                ('movie_rating', models.CharField(max_length=200)),
                ('nationality', models.CharField(max_length=200)),
                ('rate', models.CharField(max_length=200)),
                ('review', models.TextField()),
                ('director', models.CharField(max_length=200)),
                ('actor', models.CharField(max_length=200)),
                ('actress', models.CharField(max_length=200)),
                ('user_view', models.CharField(max_length=200)),
                ('reviewer', models.CharField(max_length=200)),
            ],
        ),
    ]
